### PR TITLE
Update same_eds.R

### PR DESCRIPTION
**Pull request by josempozo**
It seems that I had previously put the code of same_nds here, instead of the correct same_eds.

### CODE REVIEW

**Comment by zoometh** [comment]
I will try with this (your) last version

**Comment by zoometh** [comment]
That's fine, it works.. Now, I will merge `same_eds `and `same_nds` in a `same_neds` function with a `focus`

**Comment by josempozo** [comment]
Hi Thomas,

I don't think that this will make too much sense. They are very small and
probably only useful as internal functions. Do you think that the user will
use them directly? In that case, will not make more sense a function
comparing both simultaneously (no focus choice)?

Jose

Missatge de zoometh <notifications@github.com> del dia dt., 1 de des. 2020
a les 12:57:

**Comment by josempozo** [comment]
Look at how it is explained now in the documentation list_compar.Rc

Missatge de Jose Pozo <josmpozo@gmail.com> del dia dt., 1 de des. 2020 a
les 13:13:

**Comment by zoometh** [comment]
`same_eds `and `same_nds` (now `same_neds`) offer a synthetic view of the coincidences between pairwise. They prepare **heatmaps** and **clustering** (we can develop these aspects in the `vignettes`). I guess they will be maintain as non-internal function

**Comment by zoometh** [comment]
I'm now looking for the `list_compar.Rd`

**Comment by josempozo** [comment]
Ok. I agree then. Perhaps a better name? neds is not very clear.

I have just pulled a more compact syntax the function.

I'm going not to have lunch. I will be back in 30 min.

Jose

Missatge de zoometh <notifications@github.com> del dia dt., 1 de des. 2020
a les 13:23:

**Comment by zoometh** [comment]
For the name,I do not know.. You have a proposal ?

**Comment by zoometh** [comment]
When I run `plot_compar`, I have this message: `unused argument (lbl.size)`
Like that:

```
R> plot_compar(g.compar, c(1,4), focus = "edges", doss = system.file("extdata", package = "decorr"))
Error in side_plot(g[[1]], doss, var, focus, nds.color, nds.size, eds.color,  : 
  unused argument (lbl.size)
```

I understand that call of `side_plot` in `plot_compar` has an overnumbered parameter (`focus`). No diificulties, just remove the focus parameter, but I have also noted that `plot_compar` works only for nodes: the common edges are no more displayed.

Can you arrange that ? Or have a look ?

**Comment by josempozo** [comment]
I check this now.

Missatge de zoometh <notifications@github.com> del dia dt., 1 de des. 2020
a les 14:06:

**Comment by zoometh** [comment]
I will make a break (~2 hours).

**Comment by josempozo** [comment]
Hi Thomas,

Before you go I have a question. What do you mean by overnumbered parameter
(focus)? The parameter focus in side_plot is absolutely necessary. It is in
the file and must be there.

Jose

Missatge de zoometh <notifications@github.com> del dia dt., 1 de des. 2020
a les 14:11:

**Comment by zoometh** [comment]
I will have a look now

**Comment by josempozo** [comment]
Good. Remember also the question about repeated edges.

I will need to leave in about 10 or 15 minutes.

Jose

Missatge de zoometh <notifications@github.com> del dia dt., 1 de des. 2020
a les 17:42:

**Pull request merged**
