### PR TITLE
Patch 61

### PR DESCRIPTION
**Pull request by josempozo**
Now all images are plot on the flight. No png image is saved in the installed extdata.

Removed the new device generation for each plot. It is not the best behaviour and gave problem for vignettes and paper.

Moved gis.png from extdata to docs/img. Not sure if needed anyway.

Added image versions with only 256 colours. They weight around 1/4 of the originals and the quality is visually the same.

### CODE REVIEW

**Comment by zoometh** [comment]
I already had this fails on Linux, I don't get the why. It seems a path problem.

**Comment by josempozo** [comment]
I am checking this now. Let me see.

Missatge de Thomas Huet <notifications@github.com> del dia dv., 29 de gen.
2021 a les 22:23:

**Comment by josempozo** [comment]
Hi Tom,

I have been able to install everything on Ubuntu. I could see the vignettes
and they are right. The check says 0 errors, 0 warnings, 0 notes.

I cannot see why the error in GitHub for Ubuntu. I am now running the tests
check_rhub() and check_win_devel() launched from my Mac. They should be
equivalent to the ones run by GitHub. I am still waiting for the results. I
will tell you tomorrow morning.

Best

Jose

Missatge de Jose Pozo <josmpozo@gmail.com> del dia dv., 29 de gen. 2021 a
les 22:58:

**Comment by josempozo** [comment]
Hi Tom,

All tests with check_rhub and check_win_devel have passed successfully.
Included for Linux Ubuntu. Thus, there should be no problem. We can see
which are the system definitions on the GitHub action.

Best

Jose


El ds., 30 de gen. 2021, 2:45, Jose Pozo <josmpozo@gmail.com> va escriure:

**Comment by zoometh** [comment]
I'll have a look later in the day. I'll let you know

Best

**Comment by josempozo** [comment]
Hi Tom,

I will be making only some tests now. Do not accept any pull from now on
until I tell you otherwise. I will be torturing the code trying to find
what is making the check to fail. I will then discard all pulls.

Jose

Missatge de Thomas Huet <notifications@github.com> del dia ds., 30 de gen.
2021 a les 10:17:

**Comment by zoometh** [comment]
Ok, send me a message when I have to merge

**Pull request merged**
